set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# set -g status-style 'bg=#171421'

set-option -g default-shell /bin/zsh
set -g status-style fg=default,bg=default

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# VIM mode
set -g mode-keys vi
# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"

# Switching between the last pane
bind l switch-client -l

# modern colors
set-option -ga terminal-overrides ",tmux-256color:Tc,xterm-256color:Tc"

# Fix titlebar
set -g set-titles on
set -g set-titles-string "#T"


# Mouse friendly
set -g mouse on

# Avoid date/time taking up space
set -g status-right ''
set -g status-right-length 0

set-option -g status-position bottom

# Allow kitty to passthrough to tmux
set -g allow-passthrough on
