# Kitty Configuration

# ## Gruxbox
# include ~/.config/kitty/themes/gruvbox_dark.conf
# include ~/.config/kitty/themes/catppuccin-mocha.conf

## General settings
font_family            FiraCode
# font_family            Jetbrains Mono
# font_family            UbuntuMono Nerd Font
font_size              12.5
enable_audio_bell      no
text_composition_strategy legacy
# clipboard_control      yes

# background              #282828
# Gruvbox
# background              #1c1c1c

# Firefox
# background              #2b2a33

# Catppuccin
# background              #181926

# Grubber Darker
# background              #181818

## Behavior and performance
scrollback_lines       10000
shell_integration      yes
allow_remote_control   yes

