general {
    lock-cmd = hyprlock --immediate
    before-sleep-cmd = hyprlock --immediate
    after-sleep-cmd = hyprctl dispatch dpms on
    ignore-dbus-inhibit = false
}

# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
#     on-resume = hyprctl dispatch dpms on
# }
#
# listener {
#     timeout = 600
#     on-timeout = systemctl suspend
# }
